# List of SLN codes for classes to register Lecture SLN will include 
# all sections, while section SLN will include only that section
slns:
  - 10356: []                    # ARCH 151 lecture no quiz sections needed
  - 12646: [12647, 12648, 12648] # CSE 121 w/ quiz sections
year:
  2024
quarter:
  "SPR"
